# configs/model/deepVAR.yaml
name: deepAR
compute_flops: False
plot_forecasts: True
params:
  beta: 1.0
  num_hypotheses: 4
  num_layers: 2
  num_cells: 40
  cell_type: "LSTM"
  num_parallel_samples: 100
  dropout_rate: 0.1
  embedding_dimension: 0
  dist_type: LowRankMultivariateNormalOutput
  dist_params:
    dim: 370
    rank: 1
  scaling: True
  pick_incomplete: False
  time_features: Null
  conditioning_length: 100
  num_feat_dynamic_real: ${data.train.num_feat_dynamic_real}
  optim_kwargs:
    lr: 1e-3
    weight_decay: 1e-8
    patience: 10
  scaler_type: "mean"
  div_by_std: True
  minimum_std: 1e-3
  minimum_std_cst: 1e-4
  default_scale: False
  default_scale_cst: False
  add_minimum_std: False